# Generated by Django 2.0.7 on 2018-08-01 12:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=10)),
                ('currency_limit', models.FloatField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_id', models.CharField(blank=True, max_length=32)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('transaction_type', models.IntegerField()),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_time', models.TimeField(auto_now_add=True)),
                ('previous_balance', models.FloatField()),
                ('transaction_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_balance', models.FloatField()),
                ('transaction_remarks', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('transaction_date',),
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user_id', models.CharField(max_length=24)),
                ('wallet_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('wallet_created_date_and_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_balance', models.FloatField(default=0.0)),
                ('active', models.BooleanField(default=True)),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Currency')),
            ],
            options={
                'ordering': ('wallet_created_date_and_time',),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet'),
        ),
    ]
