# Generated by Django 2.0.7 on 2018-07-18 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.AutoField(primary_key=True, serialize=False)),
                ('currency_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('payment_id', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.TimeField()),
                ('previous_balance', models.FloatField()),
                ('transaction_amount', models.FloatField()),
                ('current_balance', models.FloatField()),
                ('transaction_remarks', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('user_id', models.CharField(max_length=24)),
                ('wallet_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('wallet_created_date_and_time', models.DateTimeField()),
                ('current_balance', models.FloatField()),
                ('currency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Currency')),
            ],
            options={
                'ordering': ('wallet_created_date_and_time',),
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.TransactionType'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet'),
        ),
    ]
