# Generated by Django 2.0.7 on 2018-07-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='currency_limit',
            field=models.FloatField(default=1000),
            preserve_default=False,
        ),
    ]
