# Generated by Django 2.0.7 on 2018-07-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_currency_currency_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
