# Generated by Django 2.0.7 on 2018-07-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20180723_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='current_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
