# Generated by Django 2.0.7 on 2018-07-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20180726_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_created_date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
