# Generated by Django 2.0.7 on 2018-07-26 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_auto_20180726_0626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_created_date_and_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
