# Generated by Django 2.0.7 on 2018-07-26 06:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_auto_20180726_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_created_date_and_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 6, 40, 21, 706615, tzinfo=utc)),
        ),
    ]
