# Generated by Django 2.0.7 on 2018-07-26 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_auto_20180726_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_created_date_and_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
